version: '3'
services:
  nginx:
    image: nginx:1.17.3
    container_name: ocproxy
    hostname: ocproxy
    restart: always
    ports:
      - 4443:4443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
